Bump PrettyTables to v3 (re-up of #67) (#68)
* Increase PrettyTables compat bound to 3

* Use PrettyTables text_table_borders__borderless

Fixes
ERROR: LoadError: UndefVarError:
 `TextFormat` not defined in `Crystalline`

* Replace Highlighter with TextHighlighter

Fixes
ERROR: LoadError: UndefVarError:
  `Highlighter` not defined in`Crystalline`

* Pass a Vector to formatters

Fixes
ERROR: LoadError: TypeError: in keyword argument formatters,
 expected Union{Nothing, Vector},
 got a value of type Crystalline.var"#305#306"

* Pass a Vector to highlighters

Fixes
ERROR: LoadError: TypeError: in keyword argument highlighters,
  expected Vector{PrettyTables.TextHighlighter},
  got a value of type
  Tuple{PrettyTables.TextHighlighter, PrettyTables.TextHighlighter}

* Replace header_crayon with style

* Update header to column_labels

* Update row_label_alignment to row_label_column_alignment

* Update hlines and vlines to TextTableFormat

* Update MultTable to PrettyTables v3

* Update compact_print_matrix to PrettyTables v3

* Fix MultTable vertical lines

* Use a compact layout for the inner matrix table

Avoid margins around the inner table.

* Update AbstractCharacterTable to PrettyTables v3

* Fix BandRepSet vertical lines

* Fix horizontal line before µ

* Extend the IOContext displaysize

This avoid ellipsis like
-                3 rows omitted
which prevented observed and expected to match.

* a few follow-up fixes

* updates to affected tests of `show`

---------

Authored-by: ederag <edera@gmx.fr>